#ifndef ACTIONS_H
#define ACTIONS_H

enum ACTION_ENUM
{
	ACTION_MOVE_UP         		= 0x00,  
	ACTION_MOVE_DOWN 			= 0x01,
	ACTION_MOVE_LEFT			= 0x02,
	ACTION_MOVE_RIGHT			= 0x03,
	ACTION_RAYCAST				= 0x04,
	ACTION_JUMP					= 0x05,
	ACTION_USE_OBJECT			= 0x06,
	ACTION_DROP_OBJECT			= 0x07,
	ACTION_SHOOT				= 0x08,
	ACTION_DEPLOY_TRAP			= 0x09,
	ACTION_RESET_RECEIVER		= 0x10,
	ACTION_CHANGE_SPELL_UP 		= 0x11,
	ACTION_CHANGE_SPELL_DOWN 	= 0x12
};

#endif