#ifndef LOADINGSTATEMENTS_H
#define LOADINGSTATEMENTS_H

static std::string LoadingStatements[] = {
    "Preparing Random Quotes",
    "Partitioning Social Network",
    "Prelaminating Spell Inventory",
    "Blurring Reality Lines",
    "Reticulating 3D Torrezno",
    "Preparing Sorcerer Simulator",
    "Capacitating Genetic Modifiers",
    "Destabilizing Orbital Particles",
    "Branching Alliances",
    "Manipulating Modal Memory",
    "Pressurizing Poison Potion",
    "Testing Wizard Telecommunications",
    "Priming Genie Brains Coefficients",
    "Caffeinating Warlock Body",
    "Initializing Secret Societies",
    "Securing Grail Position",
    "Reticulating Graduated Torrezno",
    "Requisitioning Sorcerer Donations",
    "Loading Castle Spirit Algorithm",
    "Shampooing Dirty Warlocks",
    "Restocking Lobby Inventories",
    "Compositing Spectral Complexions",
    "Replacing Wheel Bearings",
    "Re-Re-Re-Re-Reticulating Torrezno",
    "Loading 'Ghost' Sounds",
    "Turning On Turn-Ons",
    "Preparing a Tasty Grilled ",
    "Infuriating Furious Bits",
    "Flavorizing Side-Dishes",
    "Disgruntling NPCs",
    "Managing Managers' Managers",
    "Configuring Lemony Squeezation",
    "Preparing Bacon for Teleport",
    "Mitigating Time Discontinuities",
    "Reticulated Torrezno for Sale: $2",
    "Neutralizing Shuriken Oxidization",
    "Dance = Dance(1/3*pi*r^2*h)",
    "Gleefully Stacking Inventories",
    "De-chlorophyllizing Spiders",
    "Predicting AI Prevalence",
    "Calculating Dummy Trajectories",
    "Is This A Loading Screen",
    "Assessing Fog Particle Sizes",
    "Checking Diabeto Boy Sugar",
    "Individualizing Sorcerer Names",
    "Hydrating Mana Potion",
    "Stocking Pedro's Sandwiches",
    "Originating Ocean Currents",
    "Preparing Vacation Days",
    "Spawning Sights to See",
    "Reticulating Ninja Torrezno",
    "Analyzing Bomb Trajectories",
    "Training Tour Guides",
    "Initializing AI Schemes",
    "Factoring Z80 Assembly Enthusiasm",
    "Calculating Lifetime Aspirations",
    "Predicating Predestined Paths",
    "Populating Castle with potions",
    "Thinking Original quotes",
    "Reticulating Torrezno in the Zone",
    "Recruiting Ninja Judges",
    "Breaking Down Restorable Fountains",
    "Boilling Water For Onion Dry Soup",
    "Going Castle Hunting",
    "Determining Rent Guidelines",
    "Preparing Pillow Fortress",
    "Generating Compatible Castlemates",
    "Twisting Spiral Staircases",
    "Telling Torrezno to Reticulate",
    "Making a Little Bit of Magic",
    "Rasterizing Reputation Algorithms",
    "Cluttering Wardrobes",
    "Perfecting Playground Pieces",
    "Dragon-proofing Dressers",
    "Enhancing Crown Reflectivity",
    "Modeling LowPoly thugs",
    "Cultivating Quality and Swag",
    "Proscribing Voters Brain",
    "Falsifying Faux Votation",
    "Invigorating Dull Habitations",
    "Abolishing NPCs Posturing",
    "Buffing Torrezno for Reticulation",
    "Simulating Sparkling Surfaces",
    "Programming Shadows With Dots",
    "Reverse-Engineering KKrieger",
    "Unfolding Foldy Chairs",
    "Rehearsing Dinner",
    "Crash-Proofing Objective Machine",
    "Mingwling",
    "Reticulating Underwater Torrezno",
    "De-inviting Java",
    "Borrowing Something Blue",
    "Borrowing Something Purple",
    "Happy 14th Birthday Torrezno!",
    "Applying Lampshade Headwear",
    "Developing Delicious Designs",
    "Filtering Musty Horchata",
    "Reticulating Torrezno, Dude",
    "Making a Mess",
    "Capturing Magical Exuberance",
    "Growing Greener Gardens",
    "Making Manic Mansions",
    "Fiercely Reticulating Torrezno",
    "Storing Programmers Soul Energy",
    "Stopping To Smell The Flowers",
    "Increasing Neurone Population",
    "Redistributing Resources",
    "Redistributing Grials",
    "Reticulating Torrezno Again",
    "Canceling Un-cancelable Actions",
    "Matching Walls and Floors",
    "Enforcing Storyline",
    "Generating Intrigue",
    "Launching WW 9000",
    "Whipping Artist To Animate Faster",
    "Deactivating Story Arc",
    "Concatenating Random Words",
    "Balancing Voters Coefficients",
    "Re-Inverting Career Ladder",
    "Mapping Influence Attributes",
    "Aggregating Need Agents",
    "Reticulating Torrezno",
    "Interpreting Family Values",
    "Controlling NPC Controls",
    "Maximizing Social Network",
    "Generating Spaghetti Algorithm",
    "Populating Empyreal Entities",
    "Configuring Studio Operations",
    "Reticulating Golden Torrezno",
    "Composing Main Menu Music",
    "Spreading Rumors",
    "Calibrating Arm Animation",
    "Strengthening HUD Lines",
    "Abstracting Loading Procedures",
    "Locating Misplaced Calculations",
    "Eliminating Would-be Chicanery",
    "Tabulating Spell Effectors",
    "Reticulating Roasted Torreznos",
    "Recycling Code Of Other Games",
    "Binding Trace Enchantments",
    "Optimizing Baking Temperature",
    "Ensuring Transplanar Synergy",
    "Simulating Program Execution",
    "Fabricating Sorcery Memes",
    "Composing Melodic Euphony",
    "Compiling Reticulated Torrezno",
    "Calibrating Voters Glasses",
    "Avoiding Heap Corruption",
    "Making Best ABP Game",
};

#endif