#ifndef MENUS_H
#define MENUS_H

enum MenuType {
	MAIN_M		= 0,
	ALLIANCE_M	= 1,
	STORE_M		= 2,
	ENDMATCH_M	= 3,
	NETDEBUG_M	= 4
};

enum MenuOption {
	NO_OPT					= -1,

	MAIN_M_SINGLE			= 0,
	MAIN_M_TEXT_1			= 1,
	MAIN_M_CLIENT			= 2,
	MAIN_M_SERVER			= 3,
	MAIN_M_IP				= 4,
	MAIN_M_WINDOW			= 5,
	
	ALLIANCE_M_TEXT_1		= 6,
	ALLIANCE_M_WARLOCK 		= 7,
	ALLIANCE_M_WIZARD		= 8,
	ALLIANCE_M_WINDOW		= 9,

	ENDMATCH_M_TEXT_1		= 10,
	ENDMATCH_M_CONFIRM		= 11,
	ENDMATCH_M_WINDOW		= 12,

	NETDEBUG_M_P1			= 13,
	NETDEBUG_M_P2			= 14,
	NETDEBUG_M_P3			= 15,
	NETDEBUG_M_P4			= 16,
	NETDEBUG_M_P5			= 17,
	NETDEBUG_M_P6			= 18,
	NETDEBUG_M_P7			= 19,
	NETDEBUG_M_P8			= 20,
	NETDEBUG_M_WINDOW		= 21
};

#endif