#ifndef Names_H
#define Names_H

static std::string defaultNames[] = {
    "Billy",
    "Weener",
    "Klunk",
    "Pidge",
    "Snizzle",
    "Cloghopper",
    "Noggin",
    "Nadger",
    "Snuffit",
    "Wilf",
    "Bosnia",
    "Calvin",
    "Kelvin",
    "Nogbert",
    "Satch",
    "Horatio",
    "Whelk",
    "Beany",
    "Flump",
    "Sass",
    "Stumpy",
    "Pinkie",
    "Jarp",
    "Blobbo",
    "Tulip",
    "Dippy",
    "Fishface",
    "Sponge",
    "Creamcake",
    "Creambun",
    "Puffbunny",
    "Bunnykins",
    "Jack D",
    "Boggy B",
    "Spadge",
    "Fruity",
    "Dobbin",
    "Sveed",
    "Speen",
    "Keith",
    "Tebbit",
    "Creamster",
    "Soapy",
    "Sop",
    "Fudge",
    "Knuckle",
    "Neekap",
    "Dult",
    "Floppy",
    "Squeezy",
    "Shameless",
    "Rex",
    "Helmut",
    "Beaker",
    "Slim",
    "Prodder",
    "Proudfoot",
    "Ginger",
    "Eclair",
    "Walls",
    "Ironside",
    "Samson",
    "Spanky",
    "Razz",
    "Razzo",
    "Rizzo",
    "Fink",
    "Rat",
    "Phantom",
    "Goober",
    "Spectre",
    "Spookster",
    "Trenton",
    "Clifford",
    "Babe",
    "Lippy",
    "Detroit",
    "Marlon",
    "Ray",
    "Mitch",
    "Ainsley",
    "Kingston",
    "Savio",
    "Skinner",
    "Norman",
    "Belle",
    "Belly",
    "Flapper",
    "Tapper",
    "Clapper",
    "Stan",
    "Maximillian",
    "Maxwell",
    "Jack Spratt",
    "Jack Horner",
    "Miss Tuffett",
    "Prancer",
    "Roller",
    "Dudley",
    "Perky",
    "Pinky",
    "Alan",
    "Bomber",
    "Travis",
    "Ayrton Twigg",
    "Ether Trogg",
    "Mr. Spoon",
    "Doll",
    "Yellowbelly",
    "Boomshanka",
    "Scummy",
    "Mouldy",
    "Beefy",
    "Rusty",
    "Scotty",
    "Billy",
    "Larry",
    "Barry",
    "Harry",
    "Roman",
    "Fritter",
    "Gas Pipe",
    "Bopper",
    "Topper",
    "Plopper",
    "Dinky",
    "Clinky",
    "Clanky",
    "Freeman",
    "Truman",
    "Ed Statue",
    "TJ",
    "CJ",
    "Hooker",
    "Marsellus",
    "Mia",
    "Wallace",
    "Barnes",
    "Elias",
    "Charlie",
    "Sheen Man",
    "Whizzman",
    "Ice Man",
    "Spice Man",
    "Swatter",
    "Fly Swatter",
    "Brains",
    "Troy",
    "Mclure",
    "Cagney",
    "Columbo",
    "Scooby",
    "Mrs Cabletwitch",
    "Bananafeller",
    "Treewaller",
    "Treewick",
    "Pieman",
    "Lardman",
    "Mr. Lardtree",
    "Bellylard",
    "Hoover",
    "Fleabag",
    "Teabag",
    "Creamcheese",
    "Tremara",
    "Tremblewick",
    "Chegwin",
    "Cheggers",
    "Edmonds",
    "Barrymore",
    "Baker",
    "Monkhouse",
    "Turner",
    "Geri",
    "Scary",
    "Sporty",
    "Baby",
    "Courtney",
    "Anniston",
    "Noel",
    "Liam",
    "Boneman",
    "Crimpolene",
    "Seventies Man",
    "Seventies Babe",
    "Soul Man",
    "Mike Green",
    "Jamie M. Torch",
    "Rufus Brevett",
    "Skinner",
    "Normanton",
    "Trevor Parsons",
    "Milo Deville",
    "Venus Demilo",
    "Brian Damage",
    "Flick Montana",
    "Rene Artois",
    "Colonel Mustard",
    "The Prince",
    "Lady Marmalade",
    "Two Bit Charlie",
    "Brucey",
    "Jessie",
    "Bo",
    "Luke",
    "Daisy",
    "Cleetus",
    "Roscoe",
    "Coltrane",
    "Aston",
    "Korby",
    "Wallace",
    "Clive",
    "Benny",
    "Pedro",
    "Angelo",
    "Stavros",
    "Husker",
    "Winston",
    "Dunstan",
    "Blinkers",
    "Weeble",
    "Herbert",
    "Gordon",
    "Back Slapper",
    "Wriggler",
    "Troy",
    "Tiddler",
    "Python",
    "Flute",
    "Bertha",
    "Sid",
    "Chuckle Brother",
    "Cravat Man",
    "Lenny",
    "Tucker",
    "Mucker",
    "Ducker",
    "Mulligan",
    "O'Hare",
    "Victor",
    "Nursey",
    "Queeny",
    "Jim",
    "Olive",
    "Squiggly",
    "Alf",
    "Mavis",
    "Bert",
    "Flossy",
    "Sheepnut",
    "Joker",
    "Comedian",
    "Bighands",
    "Afross",
    "Mr Wiggly",
    "Pob",
    "Mr Meeker",
    "Jeremy",
    "Miss Popov",
    "Duke",
    "Starsky",
    "Hutch",
    "Bodie",
    "Doyle",
    "Malone",
    "Elliot",
    "Sputnik",
    "Monkey",
    "Tripitaka",
    "Pigsy",
    "Sandy",
    "Kingpin",
    "Boot",
    "Fox",
    "Moose",
    "Buzz",
    "Woody",
    "Jezebel",
    "Hoe",
    "Crispin",
    "Zack",
    "AC Slater",
    "Screetch",
    "Fonz",
    "Chatchie",
    "Joanie",
    "Ritchie",
    "Johnboy",
    "Jimbob",
    "Jeggett",
    "Vera",
    "Beck",
    "Keith",
    "Nigel",
    "Dervy",
    "Sheep Head",
    "Dennis",
    "Walter",
    "Rod",
    "Rizzo",
    "Heffer",
    "Bagpuss",
    "Tiffany",
    "Roger",
    "Shrubber",
    "Quincy",
    "The Face",
    "Hannibal",
    "Matey",
    "Dolphin",
    "Dougal",
    "Douglas",
    "Simpson",
    "Barney",
    "Krusty",
    "Eddy",
    "King Rollo",
    "Big Daddy",
    "Frank Black",
    "Scrappy",
    "Rocky",
    "Adrian",
    "Totty",
    "Thelma",
    "Louise",
    "Bjorn",
    "Hairspun",
    "Ozzy",
    "Bungle",
    "Lister",
    "Rimmer",
    "Holly",
    "Skeet",
    "Jambo",
    "Jarvis",
    "Marlene",
    "Kayleb",
    "Isaac",
    "Stoofer",
    "Victor Kiam",
    "Coco",
    "Itchy",
    "Scratchy",
    "Crabapple",
    "Cheesy",
    "Punjab",
    "Vindaloo",
    "Tikka",
    "Pilau",
    "Tiger Man",
    "Black Panther",
    "Gandalf",
    "Speedsta",
    "Skulkrusha",
    "Geoffrey",
    "Bungle",
    "Zippy",
    "George",
    "Cat",
    "Martian",
    "K'spoosh",
    "V'kar",
    "Froooom",
    "Sheridan",
    "Ivanova",
    "Franklin",
    "Psycho",
    "Nutter",
    "Wierdo",
    "Looney",
    "Stoned",
    "Blasted",
    "Floater",
    "Happy",
    "Raptor",
    "Cyberap",
    "Riptor",
    "Velirap",
    "Shemp",
    "Larry",
    "Moe",
    "Curly",
    "Laguna",
    "Derek Vim",
    "Marcus",
    "Yom",
    "Yim",
    "Yadam",
    "D'Artagnan",
    "Athos",
    "Porthos",
    "Aramis",
    "Crook",
    "Clamydia",
    "Capt. Molo",
    "Bantu",
    "Zorkki",
    "Isabella",
    "Tiffany",
    "Juli",
    "Dolly",
    "Emmi",
    "Elvis",
    "Tex",
    "Mex",
    "Yankee Doodle",
    "Jeff",
    "Rob",
    "Fred",
    "Martin",
    "Archie",
    "Hawking",
    "Einstein",
    "Newton",
    "Mulder",
    "Scully",
    "Skinner",
    "Don",
    "Tony",
    "Alex",
    "Soloman",
    "Bekki",
    "Wanda",
    "Susan",
    "Jules",
    "Vincent",
    "Butch",
    "Fred",
    "Wilma",
    "Barney",
    "Betty",
    "Slayer",
    "Clagnut",
    "Chuckie",
    "Tommy",
    "Phil",
    "Lil",
    "Fabio",
    "Wilbur",
    "Jimi",
    "Dave",
    "Lemmy",
    "Underdog",
    "Slave",
    "Peon",
    "Stix",
    "Grant",
    "Cassy",
    "Poncho",
    "Wigger",
    "Hootie",
    "Bates",
    "Sonny",
    "Rick",
    "Mike",
    "Neil",
    "Joseki",
    "Sentai",
    "Strepto",
    "Jaws",
    "Wolf",
    "Sandra",
    "Gillian",
    "Drew",
    "Dawn",
    "Sunny",
    "Venus",
    "Viking",
    "Prentice",
    "Horza",
    "Scabby",
    "Squidgie",
    "Fluffie",
    "Cuddlie",
    "Bunnie",
    "Cutie",
    "Hannibal",
    "Murdoch",
    "Log",
    "Lard",
    "Gravy",
    "Fumble",
    "Milo",
    "Otis",
    "Puma",
    "Guster",
    "Flusher",
    "Burp",
    "Bliss",
    "Sven",
    "Dr. Stupid",
    "Mooncow",
    "Jerky",
    "Frank",
    "Sol",
    "Abibe",
    "Pico",
    "Gurney",
    "Duncan",
    "Baz",
    "Gaz",
    "Tel",
    "Bucket",
    "Pipe",
    "Boffin",
    "Funky B",
    "Nimo",
    "Deeko",
    "Merlin",
    "Pug",
    "Arnie",
    "Jean-Claude",
    "Sly",
    "Kylie",
    "Soulhunter",
    "Sisko",
    "Kira",
    "Dax",
    "Conan",
    "Zorro",
    "Druss",
    "Waylander",
    "Fat Agnus",
    "Paula",
    "Denise",
    "Alice",
    "Plumsy",
    "Whizzo",
    "Jiggle",
    "Garfield",
    "Jon",
    "Groucho",
    "Chico",
    "Harpo",
    "Zeppo",
    "Zitter",
    "Harl",
    "Cecil",
    "Archibald",
    "Gordon",
    "Benney",
    "Doogle",
    "Florence",
    "Marge",
    "Shrapnel",
    "Purdey",
    "Gambit",
    "Doodah",
    "Jarvis",
    "Whiplash",
    "Buster",
    "Anders",
    "Floyd",
    "Roger",
    "Dave",
    "Rick",
    "Nick",
    "Manwell",
    "Burger",
    "Hot Dog",
    "Moogie",
    "Babs",
    "James",
    "Bob",
    "Wilfred",
    "Chucky",
    "Fluffy",
    "Rusty",
    "Buddy",
    "Tagbottom",
    "Mavis Fipp",
    "Morgonhorn",
    "Errol Trout",
    "Shorty Mcnostril",
    "Pasty Bloater",
    "Captain Toenail",
    "Ronnie Rampant",
    "Dr. Spangle",
    "Snake Bitey",
    "Arthur Fab",
    "Mr. Pallet",
    "J.P.Dribbler",
    "Alvin Flummox",
    "Uncle Rory",
    "Monroe",
    "Spanner",
    "Calhoun",
    "Sydney",
    "Alfred",
    "Rosanna",
    "Rosie",
    "Twoflower",
    "Creosote",
    "Elvis",
    "Bristle",
    "Mumps",
    "Pink Perm",
    "Mara",
    "Brain",
    "Pinky",
    "Plum Pie",
    "Amoeba",
    "Rattler",
    "The Kid",
    "Rodeo",
    "Pleb",
    "Biddy",
    "Boody",
    "Boola",
    "Boo",
    "Holy Sock",
    "Odd Sock",
    "Smelly Sock",
    "Wraith",
    "Brumy",
    "Kilt",
    "Sugar Cube",
    "Stuffer",
    "Bluffer",
    "Donut",
    "Cream Slice",
    "Rhubarb",
    "Lemon And Lime",
    "Lumpy Custard",
    "Curry",
    "Biriani",
    "Tikka",
    "Massala",
    "Popadom",
    "Chilli",
    "Refry",
    "Rooster",
    "Egg",
    "Balfoot",
    "Lenin",
    "Needle",
    "Woody",
    "Zulu",
    "Zeplin",
    "Skippy",
    "Soot",
    "Spooky",
    "Mr X",
    "Buddy",
    "Bullseye",
    "Bumper",
    "Thumper",
    "Tosh",
    "Blubber",
    "Cream Cheese",
    "Goaty Beard",
    "Bacon",
    "Streaky Bacon",
    "Irish Sausage",
    "Greasy Spoon",
    "Dandruff",
    "Stentch",
    "Rancid",
    "Mouldy",
    "Feeble",
    "Weeble",
    "Wally",
    "Womble",
    "Wicked",
    "Tops",
    "Nice One",
    "Rusty Nail",
    "Pavement",
    "Tarmac",
    "Concrete",
    "Roger D",
    "Wilma E",
    "Mathilda",
    "Bjorn",
    "Dr.Awesome",
    "Max",
    "Max The Great",
    "Saskia",
    "Probe",
    "Robinson",
    "Finesse",
    "Spanner",
    "Gunk",
    "Oik",
    "Wart",
    "Snatter",
    "Henry",
    "Rupert",
    "Albert",
    "George",
    "Rudolf",
    "Snidel Fighter",
    "Olly",
    "Rooster",
    "Chicken Legs",
    "Sparrow Legs",
    "Prawn",
    "Prannock",
    "Fiend",
    "Little Devil",
    "Parrot Face",
    "Bunnion Head",
    "Warped",
    "Onion",
    "Gibbering Fool",
    "Solicitor",
    "Eric",
    "Dongle",
    "Fraznist",
    "Underpants",
    "Jenna Tools"
};

#endif