#ifndef NETWORKSTRUCTS_H
#define NETWORKSTRUCTS_H

#include "RakNetIncludes.h"

enum GameLevelMessages{
	/*ID_PLAYER_JOIN = ID_USER_PACKET_ENUM + 1,
	ID_PLAYER_MOVE = ID_USER_PACKET_ENUM + 2,
	ID_EXISTING_PLAYER = ID_USER_PACKET_ENUM + 3,
	ID_PLAYER_DISCONNECT = ID_USER_PACKET_ENUM + 4*/
	ID_PLAYER_DISCONNECT = ID_USER_PACKET_ENUM + 1
};

#endif