TARGET := raknet_example
BINPATH = ./bin
BUILDPATH = ./obj
SOURCEPATH = ./src

CXXFLAGS = -O3 -ffast-math -g -Wall
LIBS = -lGL -lXxf86vm -lXext -lX11 -lXcursor -lsfml-graphics -lsfml-window -lsfml-system -lraknet -lpthread -lrt  -lBulletDynamics -lBulletCollision -lLinearMath

EXECUTABLE = $(BINPATH)/$(TARGET)
SRC := $(wildcard $(SOURCEPATH)/*.cpp)
OBJ = $(patsubst $(SOURCEPATH)/%.cpp, $(BUILDPATH)/%.o, $(SRC))

.PHONY: all clean

all: prepare $(OBJ)
	$(warning Creating the executable $(TARGET)...)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) $(LIBS) $(OBJ) -o $(EXECUTABLE)

obj/%.o: src/%.cpp
	$(warning Creating the binary $@...)
	$(CC) $(CFLAGS) -c $< -o $@

prepare:
	$(warning Creating the structure of the folders)
	mkdir -p $(BINPATH)
	mkdir -p $(BUILDPATH)

clean:
	$(warning Cleaning...)
	@$(RM) $(EXECUTABLE)
	@$(RM) $(OBJ)
